name: windows-release

on:
  release:
    types: [published]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: make
      run: cmake . . && msbuild pong.sln

    - name: zip
      run: Compress-Archive -Path /bin/pong -Destination windows.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            windows.zip